import assets from '../assets';
export const doctores = [
  {
    image: assets.images.doctors.Doctor1,
    name: 'Ruby Perrin',
    speciality: 'MDS - Periodontology and Oral Implantology, BDS',
    review: 17,
    address: 'Florida, USA',
    availableTime: 'Available on Fri, 22 Mar',
    fees: '$300 - $1000 ',
  },
  {
    image: assets.images.doctors.Doctor2,
    name: 'Darren Elder',
    speciality: 'BDS, MDS - Oral & Maxillofacial ',
    review: 35,
    address: 'Newyork, USA',
    availableTime: 'Available on Fri, 22 Mar',
    fees: '$50 - $300 ',
  },
  {
    image: assets.images.doctors.Doctor3,
    name: 'Deborah Angel',
    speciality: 'MBBS, MD - General Medicine, DNB - Cardiology',
    review: 27,
    address: 'Georgia, USA',
    availableTime: 'Available on Fri, 22 Mar',
    fees: '$100 - $400',
  },
  {
    image: assets.images.doctors.Doctor4,
    name: 'Sofia Brient',
    speciality: 'MBBS, MS - General Surgery, MCh - Urology',
    review: 55,
    address: 'Georgia, USA',
    availableTime: 'Available on Fri, 22 Mar',
    fees: '$200 - $700',
  },
  {
    image: assets.images.doctors.Doctor5,
    name: 'Sofia Brient',
    speciality: 'MBBS, MS - General Surgery, MCh - Urology',
    review: 55,
    address: 'Georgia, USA',
    availableTime: 'Available on Fri, 22 Mar',
    fees: '$200 - $700',
  },
  {
    image: assets.images.doctors.Doctor6,
    name: 'Sofia Brient',
    speciality: 'MBBS, MS - General Surgery, MCh - Urology',
    review: 55,
    address: 'Georgia, USA',
    availableTime: 'Available on Fri, 22 Mar',
    fees: '$200 - $700',
  },
  {
    image: assets.images.doctors.Doctor7,
    name: 'Sofia Brient',
    speciality: 'MBBS, MS - General Surgery, MCh - Urology',
    review: 55,
    address: 'Georgia, USA',
    availableTime: 'Available on Fri, 22 Mar',
    fees: '$200 - $700',
  },
  {
    image: assets.images.doctors.Doctor8,
    name: 'Sofia Brient',
    speciality: 'MBBS, MS - General Surgery, MCh - Urology',
    review: 55,
    address: 'Georgia, USA',
    availableTime: 'Available on Fri, 22 Mar',
    fees: '$200 - $700',
  },
  {
    image: assets.images.doctors.Doctor9,
    name: 'Sofia Brient',
    speciality: 'MBBS, MS - General Surgery, MCh - Urology',
    review: 55,
    address: 'Georgia, USA',
    availableTime: 'Available on Fri, 22 Mar',
    fees: '$200 - $700',
  },
  {
    image: assets.images.doctors.Doctor10,
    name: 'Sofia Brient',
    speciality: 'MBBS, MS - General Surgery, MCh - Urology',
    review: 55,
    address: 'Georgia, USA',
    availableTime: 'Available on Fri, 22 Mar',
    fees: '$200 - $700',
  },
  {
    image: assets.images.doctors.Doctor11,
    name: 'Sofia Brient',
    speciality: 'MBBS, MS - General Surgery, MCh - Urology',
    review: 55,
    address: 'Georgia, USA',
    availableTime: 'Available on Fri, 22 Mar',
    fees: '$200 - $700',
  },
  {
    image: assets.images.doctors.Doctor12,
    name: 'Sofia Brient',
    speciality: 'MBBS, MS - General Surgery, MCh - Urology',
    review: 55,
    address: 'Georgia, USA',
    availableTime: 'Available on Fri, 22 Mar',
    fees: '$200 - $700',
  },
];
